##############################
### MONITORS  & Workspaces ###
##############################

# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,auto,auto

monitor = DP-1, 3840x2160, 0x0, 1.5
monitor = DP-2, 3840x2160, 2560x0, 1.5


workspace=1,persistent,monitor:DP-1
workspace=2,persistent,monitor:DP-1
workspace=3,persistent,monitor:DP-1
workspace=4,persistent,monitor:DP-1
workspace=5,persistent,monitor:DP-1
workspace=6,persistent,monitor:DP-1
workspace=7,persistent,monitor:DP-1
workspace=8,persistent,monitor:DP-2
workspace=9,persistent,monitor:DP-2
workspace=10,persistent,monitor:DP-2

workspace = 1, default:true, monitor:DP-1
workspace = 8, default:true, monitor:DP-2

