# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-4cb96af0-cab4-4984-92ba-d47845fd6cc3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4cb96af0-cab4-4984-92ba-d47845fd6cc3".device = "/dev/disk/by-uuid/4cb96af0-cab4-4984-92ba-d47845fd6cc3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6995-8EDD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c68d0fe3-b7a6-46ce-b5d5-8bd11f64be73"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
